# OmniInsights v2.1 - Smart Questions System
# No external API keys needed! The app now uses intelligent, pre-crafted business insights.

# Optional: Customize app behavior
# APP_THEME = "light"  # or "dark"
# DEBUG_MODE = false

